draft:
	pdflatex fscd17.tex
	bibtex fscd17
	pdflatex fscd17.tex
	pdflatex fscd17.tex
	pdflatex fscd17-long.tex
	bibtex fscd17-long
	pdflatex fscd17-long.tex
	pdflatex fscd17-long.tex
clean:
	rm -f *.blg *.aux *.toc *.lof *.log *.lot *.bbl *.vtc *.out
